// apps/desktop/renderer/pages/admin/rubber-types.tsx
import { Layers, Plus, Trash2 } from 'lucide-react';
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import AdminLayout from '../../components/AdminLayout';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '../../components/ui/alert-dialog';
import { DataTable } from '../../components/ui/data-table';
import { Spinner } from '../../components/ui/spinner';
import { useToast } from '../../components/ui/use-toast';
import { rubberTypesApi } from '../../lib/api';
import { RubberType, useRubberTypeColumns } from './rubber-types/columns';

export default function RubberTypesPage() {
  const [data, setData] = useState<RubberType[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingItem, setEditingItem] = useState<RubberType | null>(null);
  const [deleteId, setDeleteId] = useState<string | null>(null);
  const { t } = useTranslation();

  const { toast } = useToast();

  // Form Data
  const [formData, setFormData] = useState({
    code: '',
    name: '',
    description: '',
    is_active: true,
  });

  const fetchData = async () => {
    try {
      setIsLoading(true);
      const res = await rubberTypesApi.getAll();
      setData(res);
    } catch (error) {
      console.error('Failed to fetch rubber types:', error);
      toast({
        title: 'Error',
        description: 'Failed to fetch rubber types.',
        variant: 'destructive',
      });
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const handleOpenCreate = () => {
    setEditingItem(null);
    setFormData({ code: '', name: '', description: '', is_active: true });
    setIsModalOpen(true);
  };

  const handleOpenEdit = (item: RubberType) => {
    setEditingItem(item);
    setFormData({
      code: item.code,
      name: item.name,
      description: item.description || '',
      is_active: item.is_active,
    });
    setIsModalOpen(true);
  };

  const handleDelete = (id: string) => {
    setDeleteId(id);
  };

  const confirmDelete = async () => {
    if (!deleteId) return;
    try {
      await rubberTypesApi.delete(deleteId);
      toast({
        title: 'Success',
        description: 'Rubber type deleted successfully.',
        variant: 'success',
      });
      fetchData();
      setDeleteId(null);
    } catch (error) {
      console.error('Failed to delete:', error);
      toast({
        title: 'Error',
        description: 'Failed to delete rubber type.',
        variant: 'destructive',
      });
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      if (editingItem) {
        await rubberTypesApi.update(editingItem.id, formData);
        toast({
          title: 'Success',
          description: 'Rubber type updated successfully.',
          variant: 'success',
        });
      } else {
        await rubberTypesApi.create(formData);
        toast({
          title: 'Success',
          description: 'Rubber type created successfully.',
          variant: 'success',
        });
      }
      setIsModalOpen(false);
      fetchData();
    } catch (error: any) {
      console.error('Failed to save:', error);
      toast({
        title: 'Error',
        description: error.response?.data?.message || 'Failed to save rubber type.',
        variant: 'destructive',
      });
    }
  };

  const columns = useRubberTypeColumns({
    onEdit: handleOpenEdit,
    onDelete: handleDelete,
  });

  const stats = React.useMemo(() => {
    return {
      total: data.length,
      active: data.filter((item) => item.is_active).length,
      inactive: data.filter((item) => !item.is_active).length,
    };
  }, [data]);

  if (isLoading) {
    return (
      <AdminLayout>
        <div className="h-[calc(100vh-100px)] w-full flex items-center justify-center">
          <Spinner size="xl" />
        </div>
      </AdminLayout>
    );
  }

  return (
    <AdminLayout>
      <div className="p-6 w-full max-w-[1400px] mx-auto space-y-8">
        {/* Header Card */}
        <div className="bg-card rounded-xl border border-border shadow-sm p-4 md:p-6 flex flex-col xl:flex-row items-center justify-between gap-6 transition-all hover:shadow-md">
          {/* Left: Title & Icon */}
          <div className="flex items-center gap-4 w-full xl:w-auto">
            <div className="p-3 bg-blue-50 dark:bg-blue-900/20 rounded-xl transition-transform hover:scale-105">
              <Layers className="h-6 w-6 text-blue-600 dark:text-blue-400" />
            </div>
            <div>
              <h1 className="text-xl font-bold tracking-tight text-foreground">
                Rubber Types Management
              </h1>
              <p className="text-sm text-muted-foreground">
                Manage rubber types and their configurations.
              </p>
            </div>
          </div>

          {/* Center: Stats Widget */}
          <div className="hidden md:flex items-center bg-background/50 rounded-xl border border-border p-1 shadow-sm">
            <div className="px-6 py-2 flex flex-col items-center min-w-[100px] border-r border-border/50 last:border-0">
              <span className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider">
                Total
              </span>
              <span className="text-lg font-bold text-foreground">{stats.total}</span>
            </div>
            <div className="w-px h-8 bg-border"></div>
            <div className="px-6 py-2 flex flex-col items-center min-w-[100px]">
              <span className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider text-green-600">
                Active
              </span>
              <span className="text-lg font-bold text-green-600">{stats.active}</span>
            </div>
            <div className="w-px h-8 bg-border"></div>
            <div className="px-6 py-2 flex flex-col items-center min-w-[100px]">
              <span className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider text-destructive">
                Inactive
              </span>
              <span className="text-lg font-bold text-destructive">{stats.inactive}</span>
            </div>
          </div>

          {/* Right: Action Button */}
          <button
            onClick={handleOpenCreate}
            className="w-full xl:w-auto inline-flex items-center justify-center rounded-lg text-sm font-medium transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground shadow-lg hover:bg-primary/90 hover:shadow-xl hover:-translate-y-0.5 h-11 px-8"
          >
            <Plus className="mr-2 h-4 w-4" />
            Add New Rubber Type
          </button>
        </div>

        {/* Data Table */}
        <div className="rounded-xl border border-border bg-card text-card-foreground shadow">
          <div className="bg-card rounded-lg border shadow-sm p-6">
            <DataTable columns={columns} data={data} searchKey="name" />
          </div>
        </div>

        {/* Create / Edit Modal */}
        {isModalOpen && (
          <div className="fixed inset-0 z-50 w-screen h-screen grid place-items-center p-4 bg-black/50 backdrop-blur-sm animate-in fade-in duration-200">
            <div className="bg-background rounded-xl shadow-2xl border border-border w-full max-w-lg overflow-hidden animate-in zoom-in-95 duration-200 relative">
              <div className="flex items-center justify-between p-6 border-b border-border bg-muted/10">
                <div>
                  <h3 className="text-xl font-bold text-foreground flex items-center gap-2">
                    {editingItem ? (
                      <Layers className="w-5 h-5 text-primary" />
                    ) : (
                      <Plus className="w-5 h-5 text-primary" />
                    )}
                    {editingItem ? 'Edit Rubber Type' : 'Add New Rubber Type'}
                  </h3>
                  <p className="text-sm text-muted-foreground mt-1">
                    {editingItem
                      ? 'Update rubber type details.'
                      : 'Add a new rubber type to the system.'}
                  </p>
                </div>
                <button
                  onClick={() => setIsModalOpen(false)}
                  className="text-muted-foreground hover:text-foreground transition-colors p-2 hover:bg-muted rounded-full"
                >
                  ✕
                </button>
              </div>

              <form onSubmit={handleSubmit} className="p-6 space-y-6">
                <div>
                  <label className="text-sm font-medium text-foreground mb-1 block">
                    Code <span className="text-destructive">*</span>
                  </label>
                  <input
                    type="text"
                    required
                    className="w-full px-3 py-2 bg-background border border-input rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 text-foreground"
                    placeholder="E.g. RT-001"
                    value={formData.code}
                    onChange={(e) => setFormData({ ...formData, code: e.target.value })}
                  />
                </div>
                <div>
                  <label className="text-sm font-medium text-foreground mb-1 block">
                    Name <span className="text-destructive">*</span>
                  </label>
                  <input
                    type="text"
                    required
                    className="w-full px-3 py-2 bg-background border border-input rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 text-foreground"
                    placeholder="E.g. Latex 100%"
                    value={formData.name}
                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  />
                </div>
                <div>
                  <label className="text-sm font-medium text-foreground mb-1 block">
                    Description
                  </label>
                  <textarea
                    rows={3}
                    className="w-full px-3 py-2 bg-background border border-input rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 text-foreground resize-none"
                    value={formData.description}
                    onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  />
                </div>
                <div className="flex items-center gap-2 p-3 border border-border rounded-lg bg-card/50">
                  <input
                    type="checkbox"
                    id="is_active"
                    checked={formData.is_active}
                    onChange={(e) => setFormData({ ...formData, is_active: e.target.checked })}
                    className="rounded border-gray-300 text-primary shadow-sm focus:ring-primary w-4 h-4"
                  />
                  <label
                    htmlFor="is_active"
                    className="text-sm font-medium text-foreground cursor-pointer select-none"
                  >
                    Active (Enabled)
                  </label>
                </div>

                <div className="flex justify-end gap-3 pt-2">
                  <button
                    type="button"
                    onClick={() => setIsModalOpen(false)}
                    className="px-4 py-2 text-sm font-medium text-muted-foreground hover:bg-muted rounded-md transition-colors"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    className="px-6 py-2 text-sm font-medium bg-primary text-primary-foreground hover:bg-primary/90 rounded-md transition-colors shadow-lg shadow-primary/20"
                  >
                    {editingItem ? 'Save Changes' : 'Create Rubber Type'}
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}

        {/* Delete Confirmation */}
        <AlertDialog open={!!deleteId} onOpenChange={(open) => !open && setDeleteId(null)}>
          <AlertDialogContent>
            <AlertDialogHeader>
              <div className="mx-auto w-12 h-12 rounded-xl bg-red-50 flex items-center justify-center mb-2">
                <Trash2 className="w-6 h-6 text-red-600" />
              </div>
              <AlertDialogTitle>Delete Rubber Type?</AlertDialogTitle>
              <AlertDialogDescription>
                This will permanently delete this rubber type.
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel onClick={() => setDeleteId(null)}>Cancel</AlertDialogCancel>
              <AlertDialogAction
                onClick={confirmDelete}
                className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
              >
                Delete
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      </div>
    </AdminLayout>
  );
}

// apps/desktop/src/views/admin/RubberTypes.vue
<script setup lang="ts">
import { Button } from '@/components/ui/button';
import DataTable from '@/components/ui/data-table/DataTable.vue';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Skeleton } from '@/components/ui/skeleton';
import { Textarea } from '@/components/ui/textarea';
import { rubberTypesApi, type RubberType } from '@/services/rubberTypes';
import type { ColumnDef } from '@tanstack/vue-table';
import { ArrowUpDown, Edit, Layers, Plus, Search, Trash2 } from 'lucide-vue-next';
import { computed, h, onMounted, ref } from 'vue';

// State
const rubberTypes = ref<RubberType[]>([]);
const isLoading = ref(true);
const searchQuery = ref('');
const statusFilter = ref('ALL');
const isModalOpen = ref(false);
const isDeleteModalOpen = ref(false);
const itemToDelete = ref<string | null>(null);

// Form State
const editingItem = ref<RubberType | null>(null);
const formData = ref({
  code: '',
  name: '',
  description: '',
  is_active: true,
});

// Computed Stats
const stats = computed(() => {
  return {
    total: rubberTypes.value.length,
    active: rubberTypes.value.filter((item) => item.is_active).length,
    inactive: rubberTypes.value.filter((item) => !item.is_active).length,
  };
});

// Filtered Data
const filteredData = computed(() => {
  let data = rubberTypes.value;

  // Status Filter
  if (statusFilter.value !== 'ALL') {
    const isActive = statusFilter.value === 'ACTIVE';
    data = data.filter((item) => item.is_active === isActive);
  }

  // Search Filter
  if (searchQuery.value) {
    const lowerQuery = searchQuery.value.toLowerCase();
    data = data.filter(
      (item) =>
        item.name.toLowerCase().includes(lowerQuery) || item.code.toLowerCase().includes(lowerQuery)
    );
  }

  return data;
});

// Actions
const fetchData = async () => {
  try {
    isLoading.value = true;
    rubberTypes.value = await rubberTypesApi.getAll();
  } catch (error) {
    console.error('Failed to fetch rubber types:', error);
  } finally {
    isLoading.value = false;
  }
};

const handleOpenCreate = () => {
  editingItem.value = null;
  formData.value = { code: '', name: '', description: '', is_active: true };
  isModalOpen.value = true;
};

const handleOpenEdit = (item: RubberType) => {
  editingItem.value = item;
  formData.value = {
    code: item.code,
    name: item.name,
    description: item.description || '',
    is_active: item.is_active,
  };
  isModalOpen.value = true;
};

const handleSubmit = async () => {
  try {
    if (editingItem.value) {
      await rubberTypesApi.update(editingItem.value.id, formData.value);
    } else {
      await rubberTypesApi.create(formData.value);
    }
    isModalOpen.value = false;
    await fetchData();
  } catch (error) {
    console.error('Failed to save:', error);
  }
};

const handleDeleteClick = (id: string) => {
  itemToDelete.value = id;
  isDeleteModalOpen.value = true;
};

const confirmDelete = async () => {
  if (!itemToDelete.value) return;
  try {
    await rubberTypesApi.delete(itemToDelete.value);
    isDeleteModalOpen.value = false;
    itemToDelete.value = null;
    await fetchData();
  } catch (error) {
    console.error('Failed to delete:', error);
  }
};

// Column Definitions
const columns: ColumnDef<RubberType>[] = [
  {
    accessorKey: 'code',
    header: ({ column }) => {
      return h(
        Button,
        {
          variant: 'ghost',
          onClick: () => column.toggleSorting(column.getIsSorted() === 'asc'),
        },
        () => ['Code', h(ArrowUpDown, { class: 'ml-2 h-4 w-4' })]
      );
    },
    cell: ({ row }) => h('div', { class: 'font-medium' }, row.getValue('code')),
  },
  {
    accessorKey: 'name',
    header: ({ column }) => {
      return h(
        Button,
        {
          variant: 'ghost',
          onClick: () => column.toggleSorting(column.getIsSorted() === 'asc'),
        },
        () => ['Name', h(ArrowUpDown, { class: 'ml-2 h-4 w-4' })]
      );
    },
    cell: ({ row }) => h('div', row.getValue('name')),
  },
  {
    accessorKey: 'description',
    header: 'Description',
    cell: ({ row }) =>
      h('div', { class: 'text-muted-foreground' }, row.getValue('description') || '-'),
  },
  {
    accessorKey: 'is_active',
    header: () => h('div', { class: 'text-center w-full' }, 'Status'),
    cell: ({ row }) => {
      const isActive = row.getValue('is_active');
      return h('div', { class: 'flex justify-center' }, [
        h(
          'span',
          {
            class: [
              'inline-flex items-center justify-center rounded-md px-1.5 py-0 text-[9px] font-bold uppercase tracking-wide h-5 min-w-[60px]',
              isActive ? 'bg-emerald-500/10 text-emerald-500' : 'bg-muted text-muted-foreground',
            ].join(' '),
          },
          isActive ? 'Active' : 'Inactive'
        ),
      ]);
    },
  },
  {
    id: 'actions',
    enableHiding: false,
    header: () => h('div', { class: 'text-right' }, 'Actions'),
    cell: ({ row }) => {
      const item = row.original;
      return h('div', { class: 'flex items-center justify-end gap-2' }, [
        h(
          Button,
          {
            variant: 'ghost',
            size: 'icon',
            class: 'h-8 w-8 text-muted-foreground hover:text-foreground',
            onClick: () => handleOpenEdit(item),
          },
          () => h(Edit, { class: 'h-4 w-4' })
        ),
        h(
          Button,
          {
            variant: 'ghost',
            size: 'icon',
            class: 'h-8 w-8 text-muted-foreground hover:text-destructive',
            onClick: () => handleDeleteClick(item.id),
          },
          () => h(Trash2, { class: 'h-4 w-4' })
        ),
      ]);
    },
  },
];

onMounted(() => {
  fetchData();
});
</script>

<template>
  <div class="p-6 space-y-8 max-w-[1600px] mx-auto">
    <!-- Header / Stats -->
    <div class="p-6 rounded-xl border border-border bg-card shadow-sm relative overflow-hidden">
      <div class="absolute top-1/2 right-12 -translate-y-1/2 pointer-events-none opacity-5">
        <Layers class="w-64 h-64" />
      </div>

      <div class="flex items-center justify-between gap-6 relative z-10">
        <!-- Title Section -->
        <div class="flex items-center gap-6">
          <div
            class="p-4 bg-primary/10 rounded-xl text-primary flex items-center justify-center h-16 w-16"
          >
            <Layers class="h-8 w-8" />
          </div>
          <div>
            <h1 class="text-2xl font-bold tracking-tight text-foreground">Rubber Types</h1>
            <p class="text-sm text-muted-foreground mt-1">
              Manage rubber type classifications and codes.
            </p>
          </div>
        </div>

        <!-- Stats Section -->
        <div class="flex items-center gap-8">
          <div class="text-center">
            <div class="text-xs font-bold text-muted-foreground uppercase tracking-wider mb-1">
              Total
            </div>
            <div class="text-3xl font-bold">{{ stats.total }}</div>
          </div>
          <div class="text-center">
            <div class="text-xs font-bold text-emerald-500 uppercase tracking-wider mb-1">
              Active
            </div>
            <div class="text-3xl font-bold text-emerald-500">{{ stats.active }}</div>
          </div>
          <div class="text-center">
            <div class="text-xs font-bold text-muted-foreground uppercase tracking-wider mb-1">
              Inactive
            </div>
            <div class="text-3xl font-bold text-muted-foreground">{{ stats.inactive }}</div>
          </div>
        </div>

        <!-- Add Button -->
        <div class="flex-shrink-0">
          <Button @click="handleOpenCreate" size="lg" class="shadow-lg shadow-primary/20">
            <Plus class="mr-2 h-5 w-5" />
            Add New
          </Button>
        </div>
      </div>
    </div>

    <!-- Controls & Search -->
    <div class="flex items-center justify-between gap-4">
      <div class="relative w-full max-w-sm">
        <Search class="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
        <Input v-model="searchQuery" placeholder="Search code or name..." class="pl-9" />
      </div>

      <Select v-model="statusFilter">
        <SelectTrigger class="w-[180px]">
          <SelectValue placeholder="All Status" />
        </SelectTrigger>
        <SelectContent>
          <SelectItem value="ALL">All Status</SelectItem>
          <SelectItem value="ACTIVE">Active</SelectItem>
          <SelectItem value="INACTIVE">Inactive</SelectItem>
        </SelectContent>
      </Select>
    </div>

    <!-- Loading State -->
    <div v-if="isLoading" class="space-y-4">
      <div v-for="i in 5" :key="i" class="flex items-center space-x-4">
        <Skeleton class="h-12 w-full" />
      </div>
    </div>

    <!-- Data Table -->
    <DataTable v-else :columns="columns" :data="filteredData" enable-selection />

    <!-- Create/Edit Dialog -->
    <Dialog v-model:open="isModalOpen">
      <DialogContent class="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle>{{ editingItem ? 'Edit Rubber Type' : 'Add New Rubber Type' }}</DialogTitle>
          <DialogDescription>
            {{
              editingItem
                ? 'Update the details below.'
                : 'Fill in the information to create a new rubber type.'
            }}
          </DialogDescription>
        </DialogHeader>
        <div class="grid gap-4 py-4">
          <div class="grid gap-2">
            <Label for="code">Code <span class="text-destructive">*</span></Label>
            <Input id="code" v-model="formData.code" placeholder="e.g. RT-001" />
          </div>
          <div class="grid gap-2">
            <Label for="name">Name <span class="text-destructive">*</span></Label>
            <Input id="name" v-model="formData.name" placeholder="e.g. Latex 100%" />
          </div>
          <div class="grid gap-2">
            <Label for="description">Description</Label>
            <Textarea
              id="description"
              v-model="formData.description"
              placeholder="Optional description..."
            />
          </div>
          <div class="flex items-center gap-2">
            <input
              type="checkbox"
              id="is_active"
              v-model="formData.is_active"
              class="h-4 w-4 rounded border-input text-primary focus:ring-primary"
            />
            <Label for="is_active" class="cursor-pointer">Active</Label>
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" @click="isModalOpen = false">Cancel</Button>
          <Button @click="handleSubmit">Save Changes</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>

    <!-- Delete Confirmation Dialog -->
    <Dialog v-model:open="isDeleteModalOpen">
      <DialogContent class="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Delete Rubber Type?</DialogTitle>
          <DialogDescription>
            Are you sure you want to delete this rubber type? This action cannot be undone.
          </DialogDescription>
        </DialogHeader>
        <DialogFooter>
          <Button variant="outline" @click="isDeleteModalOpen = false">Cancel</Button>
          <Button variant="destructive" @click="confirmDelete">Delete</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  </div>
</template>
